name = "Goons Tower Defense"
author = "iam4pple"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07628903e0ea86a6b9d8527bc6a70823c45372d44125b7e85fe5e56502e3e775"

[versions]
fabric = "0.16.12"
minecraft = "1.21.5"
