name = "Goons Tower Defense"
author = "iam4pple"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "769995019216f1c51723895a4f7cf9ae64eaa4dd297cec4abb56aa04c60bd8fd"

[versions]
fabric = "0.16.10"
minecraft = "1.21.5"
