name = "Goons Tower Defense"
author = "iam4pple"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b10d06e5de7e1175af1a957fb6ceb399aef6807299fc998fff1fa4c967b119dd"

[versions]
fabric = "0.16.12"
minecraft = "1.21.5"
